import os
import json
import subprocess
import re
import getpass
import platform
from fastapi import APIRouter, Request
from cms_core.api.sync import sync_blog_tree

router = APIRouter()

CURRENT_API_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_API_DIR, "..", ".."))
CONFIG_FILE = os.path.join(PROJECT_ROOT, "data", "deploy_config.json")


@router.get("/config")
async def get_deploy_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    # Source-only deployment configuration for EdgeOne Pages.
    return {
        "blogPath": "",
        "sourceRepoUrl": "",
        "sourceBranch": "main"
    }


@router.post("/config")
async def save_deploy_config(request: Request):
    try:
        data = await request.json()
        data = {
            "blogPath": str(data.get("blogPath", "")).strip(),
            "sourceRepoUrl": str(data.get("sourceRepoUrl", "")).strip(),
            "sourceBranch": str(data.get("sourceBranch", "main")).strip() or "main",
        }
        os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return {"success": True, "message": "✅ EdgeOne 部署配置已保存！"}
    except Exception as e:
        return {"success": False, "message": f"保存失败: {str(e)}"}


# 🔑 核心大升级：根据 type 动态获取/生成不同的 SSH 密匙，并自动配置路由！
@router.get("/ssh/key")
async def get_my_ssh_key(type: str = "static"):
    """获取或生成本地 SSH 公钥 (支持 A/B 双线隔离)"""
    try:
        ssh_dir = os.path.expanduser("~/.ssh")
        os.makedirs(ssh_dir, exist_ok=True)

        # 判断是为 A线(static) 还是 B线(source) 打钥匙
        if type == "source":
            key_name = "id_ed25519_source"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Source"
        else:
            key_name = "id_ed25519"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Static"

        pub_key_path = os.path.join(ssh_dir, f"{key_name}.pub")
        priv_key_path = os.path.join(ssh_dir, key_name)

        # Compatibility: reuse an existing legacy public key when requested.
        if type == "static" and not os.path.exists(pub_key_path):
            if os.path.exists(os.path.join(ssh_dir, "id_rsa.pub")):
                pub_key_path = os.path.join(ssh_dir, "id_rsa.pub")

        # 如果连指定的钥匙都没有，当场打一把新的！
        if not os.path.exists(pub_key_path):
            subprocess.run([
                "ssh-keygen", "-t", "ed25519",
                "-C", user_tag,
                "-N", "",
                "-f", priv_key_path
            ], check=True)
            pub_key_path = f"{priv_key_path}.pub"

        # Source deployments use an isolated SSH host alias and key.
        if type == "source":
            config_path = os.path.join(ssh_dir, "config")
            # 兼容 Windows 和 Mac 路径分隔符
            safe_priv_path = priv_key_path.replace('\\', '/')
            config_entry = f"\n# Auto-generated by Blog CMS for EdgeOne Source Sync\nHost github-source\n    HostName github.com\n    User git\n    IdentityFile {safe_priv_path}\n"

            config_exists = False
            if os.path.exists(config_path):
                with open(config_path, "r", encoding="utf-8") as f:
                    if "Host github-source" in f.read():
                        config_exists = True

            if not config_exists:
                with open(config_path, "a", encoding="utf-8") as f:
                    f.write(config_entry)

        # 读取公钥内容并返回给前端
        with open(pub_key_path, "r", encoding="utf-8") as f:
            key_content = f.read().strip()
            return {"success": True, "key": key_content}

    except Exception as e:
        return {"success": False, "message": f"获取 SSH 失败: {str(e)}"}


@router.post("/check")
async def check_git_env(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "本地物理路径不存在，请先检查路径！"}

        git_dir = os.path.join(blog_path, ".git")
        if not os.path.exists(git_dir):
            return {"success": False, "message": "该路径未初始化 Git 仓库，请点击下方【一键初始化】按钮。"}

        return {"success": True, "message": "✅ Git 环境正常！已准备就绪。"}
    except Exception as e:
        return {"success": False, "message": f"Git 检测失败: {str(e)}"}


@router.post("/init")
async def init_deploy_env(request: Request):
    """初始化 EdgeOne 源码部署环境。"""
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()
        source_repo = payload.get("sourceRepoUrl", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "目标博客路径不存在！"}

        if not os.path.exists(os.path.join(blog_path, "package.json")):
            return {"success": False, "message": "目标目录不是 yukiBlogs 前端项目！"}

        subprocess.run(["git", "init"], cwd=blog_path, check=True)
        if source_repo:
            subprocess.run(["git", "remote", "remove", "vercel"], cwd=blog_path, stderr=subprocess.DEVNULL)
            subprocess.run(["git", "remote", "remove", "edgeone"], cwd=blog_path, stderr=subprocess.DEVNULL)
            subprocess.run(["git", "remote", "add", "edgeone", source_repo], cwd=blog_path, check=True)

        return {"success": True, "message": "✨ Git 与 EdgeOne 源码部署环境已初始化！"}
    except Exception as e:
        return {"success": False, "message": f"初始化发生异常: {str(e)}"}


# Compatibility endpoint retained for older clients.
@router.post("/publish")
async def publish_to_github_pages(request: Request):
    await request.body()
    return {
        "success": False,
        "message": "GitHub Pages 静态发布已停用；请使用源码同步触发 EdgeOne 构建。",
    }


# ☁️ EdgeOne 源码接口：同步源代码到 GitHub 触发仓库
@router.post("/source")
async def sync_source_to_edgeone(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.isfile(os.path.join(blog_path, "package.json")):
            return {"success": False, "message": "无效的 yukiBlogs 前端路径！"}

        # 读取配置
        if not os.path.exists(CONFIG_FILE):
            return {"success": False, "message": "未找到配置文件，请先点击保存！"}

        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)

        source_repo = config.get("sourceRepoUrl", "").strip()
        source_branch = config.get("sourceBranch", "main").strip()

        if not source_repo:
            return {"success": False, "message": "源码仓库地址为空，无法同步！"}

        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._/-]*", source_branch) or ".." in source_branch:
            return {"success": False, "message": "源码分支名不合法！"}

        # Always refresh the frontend tree from the manager before committing.
        synced, sync_message = sync_blog_tree(blog_path)
        if not synced:
            return {"success": False, "message": f"前端镜像失败: {sync_message}"}

        # 1. 添加所有代码改动
        subprocess.run(["git", "add", "."], cwd=blog_path, check=True)

        # 2. 提交代码 (这里加入容错)
        subprocess.run(
            ["git", "commit", "-m", "Auto sync source code for EdgeOne"],
            cwd=blog_path,
            capture_output=True,
            text=True,
        )

        # 🌟 终极杀招：强行绑定 源码仓库专属私钥，无视 Windows 智障路由！
        ssh_dir = os.path.expanduser("~/.ssh")
        # 把 Windows 的反斜杠强制替换为正斜杠，防止 Git 识别错误
        priv_key_path = os.path.join(ssh_dir, "id_ed25519_source").replace("\\", "/")

        # 组装环境变量，用 GIT_SSH_COMMAND 强行逼迫 Git 使用这把钥匙
        custom_env = os.environ.copy()
        custom_env["GIT_SSH_COMMAND"] = f'ssh -i "{priv_key_path}" -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new'

        # 3. 推送 (携带我们强行塞进去的钥匙环境变量)
        push_process = subprocess.run(
            ["git", "push", source_repo, f"HEAD:{source_branch}"],
            cwd=blog_path,
            capture_output=True,
            text=True,
            encoding='utf-8',
            env=custom_env  # 👈 就是这里！把钥匙按在 Git 脸上！
        )

        # 判断是否成功
        if push_process.returncode != 0 and "Everything up-to-date" not in push_process.stderr:
            return {"success": False, "message": f"源码同步失败:\n{push_process.stderr}"}

        return {"success": True, "message": "☁️ 源码已成功送达 GitHub，EdgeOne 构建已触发！"}

    except Exception as e:
        return {"success": False, "message": f"源码同步引擎异常: {str(e)}"}
